### PR TITLE
Update from template

### PR DESCRIPTION
**Pull request by gvwilson**

### CODE REVIEW

**Comment by r-gaia-cs** [comment]
@gvwilson This looks good. I don't have permission to merge this.

**Comment by gvwilson** [comment]
Hm - why not?

**Comment by r-gaia-cs** [comment]
> Hm - why not?

I didn't complain with @jiffyclub when reorganizing the teams.

**Comment by jiffyclub** [comment]
Yeah there's no make-maintainers team. Should I make one, or add this repo to another team?

**Comment by gvwilson** [comment]
Hm - I think we may need an "other" team for things like this that are 
half-baked, may not make it to production, etc.  Or I can just add 
individuals?

**Comment by jiffyclub** [comment]
I don't think you can add individuals to a repo in an organization, you have to use teams.

**Pull request merged**
